apiVersion: v1
appVersion: "v2.26.0"
description: A Helm chart for Deploying Jumpserver on Kubernetes
engine: gotpl
home: https://jumpserver.org
icon: https://jumpserver.org/images/logo/favicon.ico
maintainers:
- email: support@fit2cloud.com
  name: jumpserver
sources:
- https://github.com/jumpserver/
name: jumpserver
version: 2.26.0
dependencies:
  - name: redis
    version: 0.1.1
    condition: redis.enabled
  - name: mysql
    version: 1.6.9
    condition: mysql.enabled